### ISSUE TITLE
Requesting mtlnovels

### ISSUE THREAD

**Issue by Nabeelshar** [nanihadesuka/NovelDokusha#28]
can you add mtlnovels, mtlnovel.com its the only mtl site with large amount of mtl novels.
I tired but got error , ```you have been blocked
You are unable to access mtlnovel.com```

Edited:- lol 😂
Edited 2:- WebView cookie bypass doesn't work.

**Comment by nanihadesuka** [comment]
I think the app has already enough sources, so if you want this one added take it as a challenge to make it work and do PR :) . 

Also, adding more sources doesn't add more value to the app if you already can read them form the other 10 sources we have, try adding sources only if you find novels you don't find from current sources. Remember, each source I add to the app is one source more I've to maintain and check it works (with time the scrapers will break because website will change layout and random other stuff)

**Comment by Nabeelshar** [comment]
I only add sources which matters, also this source is quite important one because there is only one of its kind.

I tried but I can't get bypass the cloud flare.

If we can get bypass the cloud flare then I will add another source wuxiaworld and remove boxnovel, webnovellight,_1stkiss and wuxia.

Then we don't need to add another source because readnovellightme(this gets from novelupdates) , mtlnovels(mtl the novels itself), novelhall (it's gets from babelnovel)  and wuxiaworld site(gets from webnovels) are the main sources.

**Comment by nanihadesuka** [comment]
#37
