### ISSUE TITLE
Since this app is free and open-source please add it in f-droid ;)

### ISSUE THREAD

**Issue by rihaq** [nanihadesuka/NovelDokusha#59]

**Comment by nanihadesuka** [comment]
Here is an independent repository (not official) from izzySoft you can use for f-droid to download the application, https://apt.izzysoft.de/fdroid/
But for now the official download location will be from the github release (I don't want more overhead)

**Comment by IzzySoft** [comment]
Speaking of free and open source: What license do the SmartToolFactory libs ship under (you use their sliders and their gesture libs)? I could not find any license information in their repo, which would make them non-free (as "all rights reserved" if no license specifies otherwise). You might wish to check before you get into trouble (just in case, not saying there's definitely trouble ahead). I've [opened an issue](https://github.com/SmartToolFactory/Compose-Colorful-Sliders/issues/4) with this which you might wish to follow, @nanihadesuka.

PS: No mark like `NonFreeDep` in my repo (yet) as I hope it was just an oversight there and will be fixed soon :crossed_fingers:
